name: NPM Release

on:
  workflow_dispatch:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          actions-cache-folder: "emsdk-cache"
          version: "4.0.10"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version: 24
          cache: "pnpm"

      - name: Build WASM
        run: |
          pnpm i
          bash ./build-wasm.sh
          pnpm build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
